# Site settings
title: Aidan Lowrie
email: your-email@example.com
description: >-
  PhD candidate exploring intelligence, cognition, and computational systems
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aidanlowrie.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag